const URL="https://hejaptzggbyqjjzireev.supabase.co",KEY="sb_publishable_FVs1qFyjyqHnr8m_4YvEaw_uZqModyE";const db=supabase.createClient(URL,KEY);const $=x=>document.getElementById(x);const money=n=>(+n||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});const L={reserviert:'Reserviert',bestaetigt:'Bestätigt',bereit:'Bereit',lieferung_geplant:'Lieferung geplant',geliefert:'Geliefert',abgeholt:'Abgeholt',abgeschlossen:'Abgeschlossen',storniert:'Storniert'};const reserve=new Set(['reserviert','bestaetigt','bereit','lieferung_geplant']);let me,inv=[],cust=[],orders=[],cat='Ballen';
function page(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));$('p-'+p).classList.add('active');document.querySelector(`nav button[data-page="${p}"]`).classList.add('active');}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>page(b.dataset.page));
async function session(){const {data:{session}}=await db.auth.getSession();if(!session){$('auth').hidden=false;$('app').hidden=true;return}me=session.user;$('auth').hidden=true;$('app').hidden=false;$('who').textContent=me.email;const {data:p}=await db.from('profiles').select('role').eq('id',me.id).maybeSingle();$('role').textContent=p?.role==='admin'?'Administrator':'Teammitglied';await load();}
$('login').onclick=async()=>{try{$('authmsg').textContent='Anmeldung läuft …';const {error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('authmsg').textContent=error?error.message:'';if(!error)await session();}catch(e){$('authmsg').textContent='Technischer Fehler: '+(e?.message||e);console.error(e);}};$('logout').onclick=async()=>{await db.auth.signOut();session();};
async function load(){const [a,b,c]=await Promise.all([db.from('inventory').select('*').order('product'),db.from('customers').select('*').order('name'),db.from('orders').select('*,customers(id,name,company),order_items(*)').order('created_at',{ascending:false})]);inv=a.data||[];cust=b.data||[];orders=c.data||[];render();}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function itemAmount(i){return +(i.amount??i.quantity??0)}function orderVal(o){return (o.order_items||[]).reduce((a,i)=>a+itemAmount(i)*(+i.unit_price||0),0)+(+o.kilometers||0)*(+o.kilometer_price||0)}function resProd(p){return orders.filter(o=>reserve.has(o.status)&&o.order_type==='Ballen').flatMap(o=>o.order_items||[]).filter(i=>i.product===p).reduce((a,i)=>a+itemAmount(i),0)}
function render(){$('custSel').innerHTML='<option value="">Kunde wählen …</option>'+cust.map(c=>`<option value="${c.id}">${esc(c.company||c.name)}</option>`).join('');$('kOpen').textContent=orders.filter(o=>!['abgeschlossen','storniert'].includes(o.status)).length;$('kRes').textContent=inv.reduce((a,i)=>a+resProd(i.product),0);$('kDel').textContent=orders.filter(o=>o.status==='lieferung_geplant').length;$('kPay').textContent=orders.filter(o=>o.payment_status!=='bezahlt'&&o.status!=='storniert').length;$('recent').innerHTML=orders.slice(0,5).map(card).join('')||'<p class="muted">Noch keine Aufträge.</p>';renderCustomers();renderOrders();renderInv();syncPrice();calc();}
document.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{document.querySelectorAll('.cat').forEach(x=>x.classList.remove('active'));b.classList.add('active');cat=b.dataset.cat;$('formTitle').textContent=cat;$('productWrap').hidden=cat!=='Ballen';$('mulchWrap').hidden=cat!=='Mulchen';if(cat==='Ballen'){$('unit').innerHTML='<option value="stueck">Stück</option>';$('amountLabel').textContent='Anzahl Ballen';$('priceLabel').textContent='Preis pro Stück (€)';}else{$('unit').innerHTML='<option value="km">Kilometer</option><option value="m2">Quadratmeter</option>';$('amountLabel').textContent='Menge';$('priceLabel').textContent='Preis pro Einheit (€)';}syncPrice();calc();});
$('unit').onchange=()=>{const u=$('unit').value;$('amountLabel').textContent=u==='km'?'Arbeitsstrecke (km)':u==='m2'?'Fläche (m²)':'Anzahl Ballen';$('priceLabel').textContent=u==='km'?'Preis pro km (€)':u==='m2'?'Preis pro m² (€)':'Preis pro Stück (€)';calc();};
function syncPrice(){if(cat==='Ballen'){const i=inv.find(x=>x.product===$('product').value);$('unitPrice').value=i?.default_unit_price||0}}
$('product').onchange=()=>{syncPrice();calc();};['amount','unitPrice','travelKm','travelPrice','roundtrip'].forEach(x=>$(x).addEventListener('input',calc));
function calc(){const a=+$('amount').value||0,p=+$('unitPrice').value||0,k=+$('travelKm').value||0,kp=+$('travelPrice').value||0;const billed=k*($('roundtrip').checked?2:1);$('total').textContent=money(a*p+billed*kp);return billed;}
$('saveOrder').onclick=async()=>{const customer_id=+$('custSel').value||null;if(!customer_id)return alert('Bitte Kunde auswählen.');const amount=+$('amount').value||0;if(amount<=0)return alert('Bitte Menge eingeben.');const u=$('unit').value;let product=cat==='Ballen'?$('product').value:cat==='Mulchen'?$('mulchType').value:cat;if(cat==='Ballen'&&reserve.has($('status').value)){const free=(inv.find(i=>i.product===product)?.quantity||0)-resProd(product);if(amount>free&&!confirm(`Nur ${Math.max(0,free)} Ballen frei. Trotzdem anlegen?`))return;}const km=calc();const {data:o,error}=await db.from('orders').insert({customer_id,order_type:cat,status:$('status').value,payment_status:'offen',delivery_type:$('delivery').value,delivery_date:$('date').value||null,kilometers:km,kilometer_price:+$('travelPrice').value||0,notes:$('notes').value.trim()||null,created_by:me.id}).select().single();if(error)return alert(error.message);const qtyLegacy=u==='stueck'?Math.round(amount):1;const {error:e2}=await db.from('order_items').insert({order_id:o.id,product,quantity:qtyLegacy,amount,unit:u,unit_price:+$('unitPrice').value||0,description:cat});if(e2){await db.from('orders').delete().eq('id',o.id);return alert(e2.message)}$('notes').value='';$('amount').value=1;await load();page('auftraege');};
$('addCustomer').onclick=async()=>{const name=$('cn').value.trim();if(!name)return alert('Name fehlt.');const {error}=await db.from('customers').insert({name,company:$('cc').value.trim()||null,phone:$('cp').value.trim()||null,email:$('ce').value.trim()||null,address:$('ca').value.trim()||null,notes:$('cno').value.trim()||null,created_by:me.id});if(error)return alert(error.message);['cn','cc','cp','ce','ca','cno'].forEach(x=>$(x).value='');await load();};$('custSearch').oninput=renderCustomers;
function renderCustomers(){const q=($('custSearch').value||'').toLowerCase();$('customers').innerHTML=cust.filter(c=>[c.name,c.company,c.phone,c.email].join(' ').toLowerCase().includes(q)).map(c=>`<div class="customer"><h4>${esc(c.company||c.name)}</h4><p>${c.company?esc(c.name)+' · ':''}${esc(c.phone||'')}${c.email?' · '+esc(c.email):''}</p></div>`).join('')||'<p class="muted">Keine Kunden.</p>';}
$('fstatus').onchange=renderOrders;$('osearch').oninput=renderOrders;function card(o){const i=(o.order_items||[])[0]||{},unit=i.unit==='m2'?'m²':i.unit==='km'?'km':'Stk.';return `<div class="order"><div class="topline"><div><h4>#${o.id} · ${esc(o.customers?.company||o.customers?.name||'Kunde')}</h4><p>${esc(o.order_type)} · ${itemAmount(i)} ${unit} · ${esc(i.product||'')} · ${money(orderVal(o))}</p></div><span class="badge ${o.status}">${L[o.status]||o.status}</span></div><p>Zahlung: <b>${o.payment_status==='bezahlt'?'Bezahlt':o.payment_status==='teilbezahlt'?'Teilbezahlt':'Offen'}</b></p><div class="actions"><select data-s="${o.id}">${Object.entries(L).map(([k,v])=>`<option value="${k}" ${o.status===k?'selected':''}>${v}</option>`).join('')}</select><select data-p="${o.id}"><option value="offen" ${o.payment_status==='offen'?'selected':''}>Offen</option><option value="teilbezahlt" ${o.payment_status==='teilbezahlt'?'selected':''}>Teilbezahlt</option><option value="bezahlt" ${o.payment_status==='bezahlt'?'selected':''}>Bezahlt</option></select></div></div>`;}
function renderOrders(){const f=$('fstatus').value,q=($('osearch').value||'').toLowerCase();$('orders').innerHTML=orders.filter(o=>(!f||o.status===f)&&[o.order_type,o.customers?.name,o.customers?.company].join(' ').toLowerCase().includes(q)).map(card).join('')||'<p class="muted">Keine Aufträge.</p>';document.querySelectorAll('[data-s]').forEach(x=>x.onchange=changeS);document.querySelectorAll('[data-p]').forEach(x=>x.onchange=changeP);}
async function changeP(e){await db.from('orders').update({payment_status:e.target.value,updated_at:new Date().toISOString()}).eq('id',+e.target.dataset.p);await load();}async function changeS(e){const id=+e.target.dataset.s,o=orders.find(x=>x.id===id),ns=e.target.value;if(o?.order_type==='Ballen'&&['geliefert','abgeholt','abgeschlossen'].includes(ns)&&!o.stock_committed){for(const it of o.order_items||[]){const ii=inv.find(x=>x.product===it.product);if(ii)await db.from('inventory').update({quantity:Math.max(0,+ii.quantity-itemAmount(it)),updated_at:new Date().toISOString(),updated_by:me.id}).eq('id',ii.id)}await db.from('orders').update({status:ns,stock_committed:true,updated_at:new Date().toISOString()}).eq('id',id)}else{await db.from('orders').update({status:ns,updated_at:new Date().toISOString()}).eq('id',id)}await load();}
function renderInv(){$('inventory').innerHTML=inv.map(i=>{const r=resProd(i.product),free=Math.max(0,+i.quantity-r);return `<div class="stock"><div><b>${i.product}</b><div class="invedit"><label>Gesamt<input data-q="${i.id}" value="${i.quantity}" type="number" min="0"></label><label>Stückpreis<input data-pr="${i.id}" value="${i.default_unit_price}" type="number" min="0" step=".01"></label></div></div><div class="metric"><b>${i.quantity}</b><small>Gesamt</small></div><div class="metric"><b>${r}</b><small>Reserviert</small></div><div class="metric"><b>${free}</b><small>Frei</small></div></div>`}).join('');document.querySelectorAll('[data-q],[data-pr]').forEach(x=>x.onchange=saveInv);}async function saveInv(e){const id=+(e.target.dataset.q||e.target.dataset.pr),q=document.querySelector(`[data-q="${id}"]`),p=document.querySelector(`[data-pr="${id}"]`);await db.from('inventory').update({quantity:+q.value||0,default_unit_price:+p.value||0,updated_at:new Date().toISOString(),updated_by:me.id}).eq('id',id);await load();}
db.auth.onAuthStateChange(()=>session());session();